### ISSUE TITLE
ListItemAttachment OnClick open wrong URL

### ISSUE THREAD

**Issue by Jospa9713** [pnp/sp-dev-fx-controls-react#1541] opened 2023-05-25 16:57 UTC
#### Category
[ ] Enhancement

[x ] Bug

[ ] Question

3.14.0 Version

Please specify what version of the library you are using: [  3.14.0  ]

#### Bug Found
When trying to open a file on the ListItemAttachments control, the URL contains duplicate parameters between the absolute url and the serverRelativeURL 
Resulting URL:  
https://TENANT.sharepoint.com/sites/SITE/_layouts/15//sites/SITE/Lists/LISTNAME/Attachments/ID/FILENAME.msg?web=1

/sites/SITE duplicated on the URL also and extra /

#### Steps to Reproduce
Use the ListItemAttachments control
Add a bunch of files with names like
File # 1.msg
File # 2.xml
File # 3.docx
Try to download any file using ListItemAttachments control

**Comment by jeremie-lopopola-nsi** [comment] 2023-05-30 10:12
Hello I have the same issue with this control anyone has a solution ?

**Comment by NishkalankBezawada** [comment] 2023-06-07 15:06
Hello @Jospa9713 & @jeremie-lopopola-nsi,

Greetings for the day.

I've discovered that the problem is being caused by the Document Cards' onClick handler. Will shortly start a Pull request.

```Typescript

```

Thanks,
Nishkalank

**Comment by jeremie-lopopola-nsi** [comment] 2023-06-09 10:41
> Hello @joelfmrodrigues,
> 
> Created a new [PR](https://github.com/pnp/sp-dev-fx-controls-react/pull/1551) to fix this issue.
> 
> Kindly review.
> 
> Thanks, Nishkalank

Thank you

**Comment by joelfmrodrigues** [comment] 2023-06-09 10:49
> Hello @joelfmrodrigues,
> 
> Created a new [PR](https://github.com/pnp/sp-dev-fx-controls-react/pull/1551) to fix this issue.
> 
> Kindly review.
> 
> Thanks, Nishkalank

Many thanks @NishkalankBezawada , will try to review it over the weekend

**Comment by NishkalankBezawada** [comment] 2023-06-09 10:57
> > Hello @joelfmrodrigues,
> > Created a new [PR](https://github.com/pnp/sp-dev-fx-controls-react/pull/1551) to fix this issue.
> > Kindly review.
> > Thanks, Nishkalank
> 
> Many thanks @NishkalankBezawada , will try to review it over the weekend

Thanks @joelfmrodrigues

**Comment by joelfmrodrigues** [comment] 2023-06-10 21:07
@Jospa9713 many thanks for reporting this. The fix from @NishkalankBezawada has been tested and merged and should be available as part of the beta release within a few minutes.

I have also tracked down when the change was introduced and found this was related to https://github.com/pnp/sp-dev-fx-controls-react/issues/1484. I tested uploading a file with the # character in the name and the character was removed, and opening the file worked as expected. I have also tried adding that file as an attachment via SharePoint UI and there was an error message saying that the character was invalid. Seems to me that SharePoint internal validation is now taking care of the special character and this is no longer an issue, so the PR does not seem to introduce https://github.com/pnp/sp-dev-fx-controls-react/issues/1484 again. All good :)

**Comment by NishkalankBezawada** [comment] 2023-06-11 17:54
Many thanks @Jospa9713 & @jeremie-lopopola-nsi for reporting. I have tried my best to find the best solution.

Many @joelfmrodrigues  for the merge and your insightful comments. 

I also saw that SharePoint handles validation; therefore, I removed the `encodeURIComponent` from the code to test, and it worked. I hope this is a long-lasting solution. 

Thanks,
Nishkalank Bezawada

**Comment by Jospa9713** [comment] 2023-06-12 18:31
Thanks @NishkalankBezawada  @joelfmrodrigues  for all the support.

**Comment by joelfmrodrigues** [comment] 2023-07-18 10:45
New release just published, closing

**Closed by joelfmrodrigues** 2023-07-18 10:45 UTC
Labels: status:fixed-next-drop, type:bug
