### ISSUE TITLE
TaxonomyPicker Suggesstion not working in SharePoint Online with no error in console

### ISSUE THREAD

**Issue by desaiprerak** [pnp/sp-dev-fx-controls-react#624] opened 2020-07-30 12:40 UTC
#### Category
[ ] Bug

#### Expected / Desired Behavior / Question
Suggestions should load

#### Observed Behavior
Suggesstion not loading

#### Error Details
Network reponse
ErrorCode: -1
ErrorMessage: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."
ErrorTypeName: "System.FormatException"
ErrorValue: null

Thanks!
Prerak

**Comment by jkib** [comment] 2020-07-30 15:16
I am having the same issue - I've spent the last day or so thinking I must have implemented the control incorrectly. Glad I'm not alone.

**Comment by desaiprerak** [comment] 2020-08-04 09:53
Is there any update on issue

**Comment by desaiprerak** [comment] 2020-08-04 10:02
> #### Category
> [ ] Bug
> 
> #### Expected / Desired Behavior / Question
> Suggestions should load
> 
> #### Observed Behavior
> Suggesstion not loading
> 
> ####Error Details
> ErrorCode: -1
> ErrorMessage: "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)."
> ErrorTypeName: "System.FormatException"
> ErrorValue: null
> 
> Thanks!
> Prerak

**Comment by jkib** [comment] 2020-08-04 17:56
Desaiprerak, my suggestions started working on Friday - though to be honest I have no idea why because I didn't make any changes to fix it. I delivered it to a user, told them that the suggestions didn't work yet, and they reported that it did work..

**Comment by TheThor59** [comment] 2020-08-12 15:14
Hello, correction is currently on the way.
I had the same issue and found bug #629 (created more recently). I tested on the dev branch and a fix has been made so it will come on next version

**Comment by jkib** [comment] 2020-08-12 15:40
Thanks!

**Comment by AJIXuMuK** [comment] 2020-08-14 23:00
Thank you @desaiprerak for reporting this.
It seems like a duplicate of #604 that has been fixed and will be available in the next version.

**Closed by AJIXuMuK** 2020-08-14 23:00 UTC
Labels: status:duplicate
