### ISSUE TITLE
Wrong documentation - LivePersona

### ISSUE THREAD

**Issue by miguelisidoro** [pnp/sp-dev-fx-controls-react#1104] opened 2022-01-28 18:09 UTC
#### Category
[ ] Enhancement

[ ] Bug

[X ] Question

#### Version

Hello,

The page at https://pnp.github.io/sp-dev-fx-controls-react/controls/LivePersona/ is showing an incorrect information on how to use LivePersona control.

import { LivePersona } from "@pnp/spfx-controls-react/lib/LivePersona";

should be replaced with 

import { LivePersona } from "@pnp/spfx-controls-react/lib/controls/LivePersona";

Can you please update the documentation?

Thanks
Miguel

**Comment by AJIXuMuK** [comment] 2022-01-29 17:41
Dupe of #1069

**Closed by AJIXuMuK** 2022-01-29 17:41 UTC
Labels: Needs: Triage :mag:
