### ISSUE TITLE
LivePersona is not working in spfx project

### ISSUE THREAD

**Issue by muppanasashikumar** [pnp/sp-dev-fx-controls-react#1241] opened 2022-06-21 14:00 UTC
Thank you for reporting an issue, suggesting an enhancement, or asking a question. We appreciate your feedback - to help the team understand your
needs please complete the below template to ensure we have the details to help. Thanks!

**Please check out the [documentation](https://pnp.github.io/sp-dev-fx-controls-react/) to see if your question is already addressed there. This will help us ensure our documentation is up to date.**

#### Category
[ ] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [    3.8.0"     ]

#### Expected / Desired Behavior / Question
Expected behavior: When Hovered on the persona the card details should pop up.

#### Observed Behavior
When hovered nothing is happening. Earlier it was working as expected but suddenly it stopped working.
#### Steps to Reproduce

`"@microsoft/sp-core-library": "1.13.1",
    "@microsoft/sp-lodash-subset": "1.13.1",
    "@microsoft/sp-office-ui-fabric-core": "1.13.1",
    "@microsoft/sp-property-pane": "1.13.1",
    "@microsoft/sp-webpart-base": "1.13.1",
    "@pnp/common": "^2.8.0",
    "@pnp/logging": "^2.8.0",
    "@pnp/sp": "^2.13.0",
    "@pnp/spfx-controls-react": "^3.8.0",
    "@pnp/spfx-property-controls": "^3.2.0",
    "bootstrap": "^5.1.1",
    "office-ui-fabric-react": "7.174.1",`

Thanks!

**Comment by divosuplente** [comment] 2022-06-22 06:25
I confirm that the component is not working. We use a custom component based on the library's LivePersona component. It suddenly stopped working like 2 days ago. No LiveCard is shown when hovering over user coins. No errors are shown in console.

**Comment by Chipui-Kasar** [comment] 2022-06-22 06:30
I started facing this issue yesterday. Let's wait for their update, hope they'll fix it ASAP.

**Comment by divosuplente** [comment] 2022-06-22 07:42
Actually, I think there's nothing the team can do to fix it. The control uses a Sharepoint component for it, and my guess is that it is that component that has suddenly stopped working. The LiveCard component this library provides is based on it

**Comment by frankyvc** [comment] 2022-06-22 08:57
+1 I'm having the same issue. Hopefully there is a quick fix, because this is a blocking issue for my client :( .

**Comment by AZNak** [comment] 2022-06-22 10:27
+1 same issue here

**Comment by Vighough** [comment] 2022-06-22 15:13
+1 same here, it seems that it has stopped working on a lot of tenants on the same time. That makes me assume that it not caused by a gradually rolled out update but rather a switch that Microsoft may have turned off

**Comment by SharePickle** [comment] 2022-06-23 10:17
It looks like Microsoft renamed property `upn` to `legacyUpn`.

**Comment by SharePickle** [comment] 2022-06-23 10:29
> > It looks like Microsoft renamed property `upn` to `legacyUpn`. Either fix it by changing component's property or maybe MS should change it back to `upn`?
> 
> Where did you find the information about this property name update?

I've debugged it and when I change `upn` to `legacyUpn` it works.

![image](https://user-images.githubusercontent.com/32567749/175278562-44c38e24-7039-402b-8dc5-3e0f017e3650.png)
![image](https://user-images.githubusercontent.com/32567749/175278731-9f16167c-e938-490a-9206-0adb3dab7a2e.png)

**Comment by muppanasashikumar** [comment] 2022-06-23 10:39
> legacyUpn



> > > It looks like Microsoft renamed property `upn` to `legacyUpn`. Either fix it by changing component's property or maybe MS should change it back to `upn`?
> > 
> > 
> > Where did you find the information about this property name update?
> 
> I've debugged it and when I change `upn` to `legacyUpn` it works.
> 
> ![image](https://user-images.githubusercontent.com/32567749/175278562-44c38e24-7039-402b-8dc5-3e0f017e3650.png) ![image](https://user-images.githubusercontent.com/32567749/175278731-9f16167c-e938-490a-9206-0adb3dab7a2e.png)

Could you please let me from where did you find this file location?

**Comment by SharePickle** [comment] 2022-06-23 10:44
> Could you please let me know from where did you find this file location?

Here's the file `https://res-1.cdn.office.net/files/sp-client/sp-webpart-shared_en-us_548b73a3d19b222579a2.js`
Line number `4904` is where it renders the card on hover.
This file could be different for you tenant, just look for `sp-webpart-shared` js file.

**Comment by divosuplente** [comment] 2022-06-23 10:53
I have implemented the change in my own component and I can confirm that it works! thank you so much @SharePickle!

**Comment by muppanasashikumar** [comment] 2022-06-23 10:54
> > Could you please let me know from where did you find this file location?
> 
> Here's the file `https://res-1.cdn.office.net/files/sp-client/sp-webpart-shared_en-us_548b73a3d19b222579a2.js` Line number `4904` is where it renders the card on hover. This file could be different for you tenant, just look for `sp-webpart-shared` js file.
> 
> Of course you can't edit MS's LivePersona file, you'd need to fix PnP library.
Great man it worked for me. Thanks a lot appreciated. You are a saviour for me. @SharePickle

**Comment by debarunbanerjee2018** [comment] 2022-06-23 10:54
> > Could you please let me know from where did you find this file location?
> 
> Here's the file `https://res-1.cdn.office.net/files/sp-client/sp-webpart-shared_en-us_548b73a3d19b222579a2.js` Line number `4904` is where it renders the card on hover. This file could be different for you tenant, just look for `sp-webpart-shared` js file.
> 
> Of course you can't edit MS's LivePersona file, you'd need to fix PnP library.

Many Many Thanks. Was struggling for past 2-3 days. Thank you so much mate. 🙏 Much love from India.

**Comment by joelfmrodrigues** [comment] 2022-06-23 11:16
@SharePickle many thanks for providing a fix!
Just to confirm, is this the change that you implemented within the LivePersona component?
![image](https://user-images.githubusercontent.com/19577724/175286461-ae72ccfa-4113-4709-9a92-eb891ed90eb9.png)

**Comment by SharePickle** [comment] 2022-06-23 11:21
> @SharePickle many thanks for providing a fix! Just to confirm, is this the change that you implemented within the LivePersona component? ![image](https://user-images.githubusercontent.com/19577724/175286461-ae72ccfa-4113-4709-9a92-eb891ed90eb9.png)

Correct. I also provided a PR with the fix.

**Comment by joelfmrodrigues** [comment] 2022-06-23 12:22
@SharePickle many thanks! will review now

**Comment by joelfmrodrigues** [comment] 2022-06-23 12:54
The PR is now merged and the fix should be available shortly in the auto-published beta release. Thanks @SharePickle !
If someone has the chance to test the beta package that will be available shortly please let us know if everything is resolved.

**Closed** 2022-06-23 22:53 UTC
Labels: status:fixed-next-drop, type:bug

**Comment by joelfmrodrigues** [comment] 2022-06-24 08:12
Hey all, just providing a quick update - 3.8.1 released as hotfix to resolve this issue
@SharePickle I will revert your changes from dev and pull them from master - I have added your name to the changes in 3.8.1 so you will still appear as contributor

**Comment by ValerasNarbutas** [comment] 2022-11-22 21:11
> [joelfmrodrigues](/joelfmrodrigues)

good day, looks like this one does not work anymore.
and also i dont see legacyUpn property in LivePersona new version component.

**Comment by SharePickle** [comment] 2022-11-22 22:21
@ValerasNarbutas did Microsoft change it back to `upn`?
Because on my tenant it looks like this (both properties supported):
![image](https://user-images.githubusercontent.com/32567749/203433055-f74d69c5-a445-4b91-a231-05d8d38bcd32.png)

Maybe renaming `legacyUpn` back to `upn` will help, but for now on my environment `LivePersona` still works.

**Comment by ValerasNarbutas** [comment] 2022-11-23 10:02
> @ValerasNarbutas did Microsoft change it back to `upn`? Because on my tenant it looks like this (both properties supported): ![image](https://user-images.githubusercontent.com/32567749/203433055-f74d69c5-a445-4b91-a231-05d8d38bcd32.png)
> 
> Maybe renaming `legacyUpn` back to `upn` will help, but for now on my environment `LivePersona` still works.

I see, well i have multiple issues. 
1. When used pnp live persona component i did not get image in people coin but hover and popup worked.
2. added a custom live persona card from @hugoabernier sample and now i get a picture in coin but hover not working.
3 hover and popup is only starting to work if i hover first out of the box person coin. When some javascript library called "some guid"_LivePersonaCard_with)react.js loaded in background and its works both on PNP component, my custom one also.

So looks like something is still missing :(

**Comment by SharePickle** [comment] 2022-11-29 10:34
@ValerasNarbutas any updates? Are you experiencing this issue still? I had issues with person's profile pic because MS updated profile picture service, but it's all good now.

**Comment by ValerasNarbutas** [comment] 2022-12-29 11:36
> @ValerasNarbutas any updates? Are you experiencing this issue still? I had issues with person's profile pic because MS updated profile picture service, but it's all good now.

hey @SharePickle looks like all good, 
For me i am using @hugoabernier component and it works, but my colleague have no issue with MS persona component.

**Comment by joelfmrodrigues** [comment] 2023-01-04 13:30
@ValerasNarbutas really sorry for the delay in replying back to you, I have been super busy with work in the last 2 months before end of year.
Based on your last reply, is this all working again for you? I assume MS must have reverted the breaking change if this is the case...

**Comment by joelfmrodrigues** [comment] 2023-01-11 09:24
@ValerasNarbutas many thanks for confirming
