### ISSUE TITLE
TaxonomyPicker suggestion not working in SharePoint Online

### ISSUE THREAD

**Issue by limcysam** [pnp/sp-dev-fx-controls-react#629] opened 2020-08-10 03:26 UTC
#### Category

[ ] Bug

#### Version

Please specify what version of the library you are using: [ 1.19.0  ]

#### Expected / Desired Behavior / Question
Suggestion load as when clicked on the icon

#### Observed Behavior
Suggestion do not load with spinning wheel in type ahead

#### Steps to Reproduce
Type in a existing term within the textbox

<img width="538" alt="TaxonomyPickerIssue" src="https://user-images.githubusercontent.com/42954663/89749896-0a2cfe00-db0d-11ea-8a4c-03026ef3d19e.png">

**Comment by Matej4386** [comment] 2020-08-12 05:18
Hello, just found out that suggestions are not working also on on-prem SP 2019.

Rest call (Payload) containst undefined parameter:
`<Method Id="6" ParentId="3" Name="GetTerm"><Parameters><Parameter Type="String">**undefined**</Parameter></Parameters></Method><Property Id="9" ParentId="6" Name="Terms" />`

it is called from:
`termsService.searchTermsByTermId(filterText, this.props.termPickerHostProps.anchorId)];`

anchorId is undefined.

Terms are loaded properly in Panel.

**Comment by Matej4386** [comment] 2020-08-12 06:25
Hmm i change some lines and now it works:

In TermPicker.js -> onFilterChanged function:
termsService.searchTermsByTermId(filterText, this.props.termPickerHostProps.**termsetNameOrID**)]; _was anchorId_

In SPTermStorePickerService.js -> searchTermsByTermId function i have replaced data with this one:
`var data =  '<Request xmlns="http://schemas.microsoft.com/sharepoint/clientquery/2009" SchemaVersion="15.0.0.0" LibraryVersion="16.0.0.0" ApplicationName="Javascript Library"><Actions><ObjectPath Id="1" ObjectPathId="0" /><ObjectIdentityQuery Id="2" ObjectPathId="0" /><ObjectPath Id="4" ObjectPathId="3" /><ObjectIdentityQuery Id="5" ObjectPathId="3" /><ObjectPath Id="7" ObjectPathId="6" /><ObjectIdentityQuery Id="8" ObjectPathId="6" /><ObjectPath Id="10" ObjectPathId="9" /><Query Id="11" ObjectPathId="6"><Query SelectAllProperties="true"><Properties /></Query></Query><Query Id="12" ObjectPathId="9"><Query SelectAllProperties="false"><Properties /></Query><ChildItemQuery SelectAllProperties="false"><Properties><Property Name="IsRoot" SelectAll="true" /><Property Name="Labels" SelectAll="true" /><Property Name="TermSet" SelectAll="true" /><Property Name="TermsCount" SelectAll="true" /><Property Name="Id" SelectAll="true" /><Property Name="Name" SelectAll="true" /><Property Name="PathOfTerm" SelectAll="true" /><Property Name="LocalCustomProperties" SelectAll="true" /><Property Name="IsDeprecated" ScalarProperty="true" /><Property Name="IsAvailableForTagging" ScalarProperty="true" /></Properties></ChildItemQuery></Query></Actions><ObjectPaths><StaticMethod Id="0" Name="GetTaxonomySession" TypeId="{981cbc68-9edc-4f8d-872f-71146fcbb84f}" /><Method Id="3" ParentId="0" Name="GetDefaultKeywordsTermStore" /><Method Id="6" ParentId="3" Name="GetTermSet"><Parameters><Parameter Type="Guid">'+ termId +'</Parameter></Parameters></Method><Method Id="9" ParentId="6" Name="GetAllTerms" /></ObjectPaths></Request>';`

Now it works.

**Comment by TheThor59** [comment] 2020-08-12 14:02
Hello,

I encountered the same issue on this component through an integration with SPFx ListCommand. I found the same issue in the query as @Matej4386 did.

@Matej4386  In terms of correction that should not be suffisant to fix that way as if I'd like to let users select or search terms in the children of a specific term of my TermSet, it should use anchorId if it's not null and, if it's null, use the TermSetId. The change of the query is pretty much mandatory to be able to search without using a sub term as root of your field.

I tested the correction of @Matej4386 and it's working for TermSet without needing an anchorId, this should be implemented.

**Comment by TheThor59** [comment] 2020-08-12 15:10
A correction has already been made on DEV so fix will arrive soon. I added a fix in a pull request that allow to directo provide result from sharepoint rest query loading list's fields. When passing the AnchorId parameter from a field's properties, the empty GUID was in use, making the suggestion query crash. I fixed this point.
We will need to wait for the next version for this fix.

**Comment by limcysam** [comment] 2020-08-13 00:41
@TheThor59 when will the next version be released?

**Comment by AJIXuMuK** [comment] 2020-08-14 23:01
Thank you @limcysam  for reporting this.
It seems like a duplicate of #604 that has been fixed and will be available in the next version.

**Closed by AJIXuMuK** 2020-08-14 23:01 UTC
Labels: status:duplicate

**Comment by limcysam** [comment] 2020-08-20 03:31
Caan you please let me know when will the next version with the fix be released?

**Comment by AJIXuMuK** [comment] 2020-08-20 03:57
@limcysam we plan to release the next version in next 2 weeks or so.
