### ISSUE TITLE
ListItemAttachments and special characters in filename

### ISSUE THREAD

**Issue by evlo** [pnp/sp-dev-fx-controls-react#801] opened 2021-02-18 21:39 UTC
#### Category
[  ] Enhancement
[x] Bug
[  ] Question

#### Version

Please specify what version of the library you are using: [1.21.1]

#### Expected / Desired Behavior / Question
if you attach file with name **doc'-'čííčářěášý@.docx** in sharepoint online name is kept
if you attach file with name **doc'-'čííčářěášý@.docx** using **ListItemAttachments** component it gets saved as **doc-.docx**
if you use sharepoint REST api  `/_api/web/GetList(@a1)/Items(@a2)/AttachmentFiles/addUsingPath(decodedUrl=@a3)?@a1=%27%&@a2=17&@a3=%27%40%2Etxt%27` so you encode **@.txt** as **%27%40%2Etxt%27** ie `encodeURIComponent('@.txt')` it works

using `this.getListByRelativeUrl(this._listUrl).items.getById(itemId).attachmentFiles.addMultiple` with `doc%27-%27%C4%8D%C3%AD%C3%AD%C4%8D%C3%A1%C5%99%C4%9B%C3%A1%C5%A1%C3%BD%40.docx` as filename fails but removing ' i'm able to save file with filename encoded as `doc-%C4%8D%C3%AD%C3%AD%C4%8D%C3%A1%C5%99%C4%9B%C3%A1%C5%A1%C3%BD%40.docx` at least using js

so if you escape apostrophes as **%27%27** ie. **doc'-'čííčářěášý@.docx**  becomes `doc%27%27-%27%27%C4%8D%C3%AD%C3%AD%C4%8D%C3%A1%C5%99%C4%9B%C3%A1%C5%A1%C3%BD%40.docx` it works in javascript/rest attachment methods

**_Expected / Desired Behavior_** 
attachment is uploaded with special characters kept

#### Observed Behavior
special characters are removed from filename

related https://github.com/pnp/sp-dev-fx-controls-react/issues/526

#### Steps to Reproduce
upload file with name **doc'-'čííčářěášý@.docx** and any content

**Comment by evlo** [comment] 2021-03-05 08:25
I just tried this on 2.5.0 and behavior is same as on 1.21.1

**Comment by kunj-sangani** [comment] 2021-03-13 06:03
Hi @AJIXuMuK ,

The issue is because of  the replace parth in the below code 
fileName.replace(/'/g, "''")

File Refernce:- [SPService.ts](https://github.com/pnp/sp-dev-fx-controls-react/blob/master/src/services/SPService.ts)
Method Name:- addAttachment

The replace code is present for all attachment related methods

Not sure if we can remove it or not can you please help on this

**Comment by AJIXuMuK** [comment] 2021-04-11 20:02
Hi @evlo,

Could you please test the latest [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/) to see if the issue is fixed for you?

**Comment by joelfmrodrigues** [comment] 2021-05-07 21:39
@evlo this should now be fixed in the latest version. Please update to the latest version and open a new issue if the problem persists.
Thanks for your contribution

**Closed by joelfmrodrigues** 2021-05-07 21:39 UTC
Labels: Good First Issue 🏆, status:fixed-next-drop, type:bug
