### ISSUE TITLE
TaxonomyPicker Does not show term set labels in Version 3.10.0 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/sp-dev-fx-controls-react#1299] opened 2022-08-31 07:17 UTC
[ X] Bug

Please specify what version of the library you are using: [  3.10.0      ] SPFx 1.15.0

#### Expected / Desired Behavior / Question
the code:
```
  <TaxonomyPicker allowMultipleSelections={false}
          termsetNameOrID="Document Type" panelTitle="Select Document Type" label="Document Type"
          context={wpContext as any} 
          initialValues={selDocType} placeholder={'Start typing or click the label'}
          onChange={onTaxPickerChange} disabled={!dpcRequest.LockedToMe}
          isTermSetSelectable={false} />
```
Should show all the labels of the  "Document Type" term set to allow selection of one.
#### Observed Behavior
It just shows the spinner forever
![image](https://user-images.githubusercontent.com/5054931/187616479-da744321-4759-4735-8751-1c859980b46a.png)

I installed 3.9.0 and it works fine now
Thanks!

**Comment by Perneel** [comment] 2022-09-06 10:21
I can confirm this is an issue with 3.10.0

**Comment by diabhoil** [comment] 2022-09-09 12:54
I can confirm that. Its not working. Same problem is reported here (https://stackoverflow.com/questions/73645337/sharepoint-framework-spfx-pnp-pnpjs-with-react-taxonomy-picker-not-working) I guess.

When I debug the code there is in the "SPTermStorePickerService.ts" there is a "this.clientServiceUrl" which is always undefined. Don't know where it should be set and where this is happening in the code?

Looks like it was removed here (https://github.com/pnp/sp-dev-fx-controls-react/commit/ea4c4b157f2b79f8977b0753ff765f3462d7f66f#diff-35527a9cbfd12287fbf47b477c5be3f4577810886202ce0e85e11eef1f6591ae)

**Comment by Ofer-Gal** [comment] 2022-09-14 15:03
Thank you.
Will there be a new version for the fix?

**Comment by AJIXuMuK** [comment] 2022-09-17 20:26
The PR has been merged and will be included in the next release.
In a meanwhile you can use [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/)

**Closed** 2022-10-04 13:27 UTC
Labels: status:fixed-next-drop

**Comment by Ofer-Gal** [comment] 2022-10-04 13:29
Thank You
