### ISSUE TITLE
Using ListView in a SharePointFullPage component

### ISSUE THREAD

**Issue by roberto-ajolfi** [pnp/sp-dev-fx-controls-react#1064] opened 2021-11-22 09:49 UTC
#### Category
[ ] Enhancement

[ ] Bug

[ X] Question

#### Version

Please specify what version of the library you are using: [  3.4.1  ]

#### Expected / Desired Behavior / Question
I've added a ListView in a SPFX component. I want to use this component as a full page component (I have added the _SharePointFullPage_ in the _supportedHosts_ setting to the part manifest).

#### Observed Behavior
The component is rendered on the page into a div that limits the height of the component, as you can see in the attached image

![ListView Behaviour](https://user-images.githubusercontent.com/4680314/142839074-1e561b3f-347b-42a2-9d65-9b8b7bf4419f.png)

#### Steps to Reproduce
- create a new Web Part with yeoman
- add the the scaffolded code a ListView component that loads data via PnP/JS
- add the _SharePointFullPage_  entry to the _supportedHosts_ setting in the part manifest
- deploy the package and create a new page using the new component

**Comment by AJIXuMuK** [comment] 2021-12-04 17:09
dupe of #1065

**Closed by AJIXuMuK** 2021-12-04 17:09 UTC
Labels: Needs: Triage :mag:
