### ISSUE TITLE
WebPartTitle Control Fails to Update After Initial Save

### ISSUE THREAD

**Issue by ACM-V** [pnp/sp-dev-fx-controls-react#1921] opened 2024-12-12 07:02 UTC
Category
[ ] Enhancement

[x] Bug

[ ] Question

Version
v3.20.0

This issue persists in previous release 3.19.0 also and an issue has been reported for the same .

**Expected Behavior**
The WebPart title should be editable dynamically every time the WebPart is in edit mode, not just during the initial setup.

**Observed Behavior**
The WebPart title can only be set once, during the initial addition of the WebPart.
The event appears to propagate correctly, but the WebPart does not re-render, leading to the observed faulty behavior.
Note: Users have reported that this faulty behavior started appearing a couple of days ago.
Forcing a re-render by adding this.render() resolves the issue, but this would require updating all existing components. Additionally, this requirement is not documented as mandatory.

_updateProperty: (value: string) => { this.properties.title = value; this.render(); }}_ 

**Steps to Reproduce:**

1. Scaffold a new SPFx React solution using SPFx v1.19.0.
2. Ensure you are using Node.js v18.20.4
3. Implement the WebPartTitle Control as per the [PnP WebPartTitle documentation](https://pnp.github.io/sp-dev-fx-controls-react/controls/WebPartTitle/).
4. Add the WebPart to a SharePoint page.
5. Publish the page.
6. Edit the page and attempt to update the WebPart title.

**Comment by joelfmrodrigues** [comment] 2024-12-12 09:07
@ACM-V I believe this is a duplicate of https://github.com/pnp/sp-dev-fx-controls-react/issues/1877
We merged a PR yesterday to address this issue. Can you please test with the beta release, version 3.21.0?
`npm i @pnp/spfx-controls-react@3.21.0-beta.1228477`

**Comment by joelfmrodrigues** [comment] 2024-12-12 11:27
@ACM-V  I will close this item as duplicate with the assumption that this is the same issue as #1877 and that it's resolved in the beta release, but please @ mention me here if you still find this issue on the beta release and I will reopen it.

**Closed by joelfmrodrigues** 2024-12-12 11:27 UTC
Labels: status:duplicate, status:fixed-next-drop
