### ISSUE TITLE
Pnp TaxonomyPicker suggestion/match does not work as expected

### ISSUE THREAD

**Issue by geltapatio** [pnp/sp-dev-fx-controls-react#604] opened 2020-07-08 06:33 UTC
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Expected / Desired Behavior / Question
you can find any term, which is part of the configurated taxonomy hierarchy 
if the user searches for a subordinate term suggestion/match will display it.

#### Observed Behavior
The suggestion/match of TaxonomyPicker only finds main terms. The subterms could not be found.

#### Steps to Reproduce

Example 

if you search with "Kap" suggestion/match will display "Kapitel1"
if you search with "Th" suggestion/match will not display results
if you search with "Ab" suggestion/match will not display results
[] Kapitel1
--- [] Thema1
--- --- [] Ablauf1
--- --- [] Ablauf2
--- --- [] Ablauf3
--- --- [] Ablauf4

![bidl1_tems](https://user-images.githubusercontent.com/9026810/87123573-56272180-c287-11ea-95dd-4474bcab3ee8.JPG)

Current Version

Main Term (Kapitel1) was found
![bild2_KapitelOK](https://user-images.githubusercontent.com/9026810/87123574-56272180-c287-11ea-9093-5f1051820298.JPG)

subordinates (Ablauf1, Ablauf1_3ToDelete, Ablauf2, Ablauf3, Ablauf4) could not be found.
![bild3_AblaufNOK](https://user-images.githubusercontent.com/9026810/87123575-56bfb800-c287-11ea-8e74-5ebff484bac8.JPG)

subordinate (Thema1) could not be found
![bild3_ThemaNOK](https://user-images.githubusercontent.com/9026810/87123576-56bfb800-c287-11ea-882a-e3cb3434d255.JPG)

Thanks!
Luis Miguel Gamiz Espinosa

**Comment by geltapatio** [comment] 2020-07-10 06:36
I already fixed it and created a pull request

**Comment by AJIXuMuK** [comment] 2020-07-12 00:41
@geltapatio - thank you for reporting and fixing the issues.

The PR has been merged and will be available in the next release.

In a meanwhile please test the functionality in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

**Comment by TheThor59** [comment] 2020-08-12 15:16
Hello @AJIXuMuK 

could we mark #624 and #629 as duplicate of this ticket as a fix has been impremented on beta ?
Alors I've just made a pull request to fix the new correction as there is an issue when using empty GUID, this is linked to this point.

Thanks

**Comment by limcysam** [comment] 2020-08-20 03:32
Caan you please let me know when will the next version with the fix be released?

**Comment by AJIXuMuK** [comment] 2020-08-20 03:58
@limcysam - we're planning to release the next version in the next two weeks or so.

**Closed** 2020-09-18 23:58 UTC
Labels: status:fixed-next-drop, type:bug
