### ISSUE TITLE
ListView - drag & drop of files not possible

### ISSUE THREAD

**Issue by mgordic** [pnp/sp-dev-fx-controls-react#803] opened 2021-02-19 12:27 UTC
#### Category
[ ] Enhancement

[ ] Bug

[ x] Question

#### Version

Please specify what version of the library you are using: [2.4.0]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
I want to implement file upload through the ListView component. Everything seems correctly set (I used code from ControlsTest.tsx) but when I try to drag and drop files, nothing happens. It's not indicating that drag & drop is allowed, there are no lines that indicate that, nothing.

Any ideas? Should I install some additional libraries to make this work?

Thanks!

**Comment by aaclage** [comment] 2021-02-19 12:30
This control just retrieves the Files object, you need to create the method to send the files.
Here a example:
http://aaclage.blogspot.com/2020/10/new-drag-and-drop-listview-pnpspfx.html

**Comment by mgordic** [comment] 2021-02-19 12:34
Hi @aaclage 

Thank you for your quick reply. I already found your blog post.

I configured everything, but unlike in your blog post's second picture, in my case, nothing happens when I drag files into ListView.

Thank you
Marko

**Comment by aaclage** [comment] 2021-02-19 12:36
Track what is returning using console.log

**Comment by mgordic** [comment] 2021-02-19 12:41
Literally nothing in console.

![screenshot](https://user-images.githubusercontent.com/4919036/108505763-31cd0200-72b8-11eb-8ca2-48c4178fb85a.png)

**Comment by aaclage** [comment] 2021-02-19 12:43
ok use key F12 from your browser to retrieve the browser "developer tools" then select tab "console" to see the logs

**Comment by mgordic** [comment] 2021-02-19 12:47
Already did that :) There is nothing. And looks totally different than the one on official site

![](https://pnp.github.io/sp-dev-fx-controls-react/assets/ListView-DragDrop.png)

Here is my code:

![image](https://user-images.githubusercontent.com/4919036/108506372-f5e66c80-72b8-11eb-8bad-41f2d86f0b72.png)

**Comment by aaclage** [comment] 2021-02-19 12:58
I will give a look but cannot reproduce from my side.

**Comment by mgordic** [comment] 2021-02-19 13:22
Looks like a problem only exists in hosted workbench. If I deploy webpart to the app catalog, then it works.

**Comment by aaclage** [comment] 2021-02-19 13:40
to test properly recommend to use SharePoint workbench /_layouts/15/workbench.aspx because of SharePoint dependencies

**Comment by mgordic** [comment] 2021-02-19 14:45
Yup, I am doing exactly like that, but anyway it's not working until deploy to the App Catalog

**Comment by mgordic** [comment] 2021-02-26 17:03
@aaclage Is it possible to extend the functionality? Right now, when you drag and drop e-mail from Outlook into web part, the e-mail got deleted from the mailbox.

**Comment by AJIXuMuK** [comment] 2021-03-19 17:17
@mgordic - we're definitely not in charge of what happening with Outlook email when you drag emails from there.
The control, as well as page where it lives is isolated and can't impact on other apps.

**Comment by AJIXuMuK** [comment] 2021-03-19 17:18
Please, let us know if @aaclage has answered your question.

**Comment by aaclage** [comment] 2021-03-19 22:01
@mgordic 

I made a test with my outlook and email stay there, strange behavior. 
Made some research regarding this and found this was happening with a specific versions of Browsers using Chromium, 
https://bugs.chromium.org/p/chromium/issues/detail?id=1066975

Some Browsers have by default object dataTransfer.dropEffect  as "**move**" that makes the behavior that you are having, move file and delete mail from outlook.
https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect 

I saw that last version of Chrome change this behavior to "none".

@AJIXuMuK 
Since the control is using the out of the box from the browser. 
I will recommended to set "dataTransfer.dropEffect = 'none'" in all drag events, this avoid possible changes from Browser changing the default value and this doesn't happen.
Do you agree?

**Comment by aaclage** [comment] 2021-03-24 08:27
@joelfmrodrigues 
As follow up.
Do you think that make sense to change to "dataTransfer.dropEffect = 'none'"

**Comment by AJIXuMuK** [comment] 2021-03-24 14:19
@aaclage - yes, we can definitely do that. I'd check the default behavior on SP document library first though.

**Comment by joelfmrodrigues** [comment] 2021-04-01 22:44
@mgordic thanks for all the feedback. @aaclage  submitted a PR that should fix this and will be available on the next release.
If you have the chance, it would be great if you could test dev-v2 and validate if it solves your problem.

**Comment by joelfmrodrigues** [comment] 2021-05-07 21:42
@mgordic closing this issue as a new version with this feature is now released. 
Thanks for your contribution

**Closed by joelfmrodrigues** 2021-05-07 21:42 UTC
Labels: status:fixed-next-drop
