### ISSUE TITLE
ListPicker stopped working in upgrade from 3.1.0 to 3.2.0

### ISSUE THREAD

**Issue by PathToSharePoint** [pnp/sp-dev-fx-controls-react#945] opened 2021-06-27 04:34 UTC
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 3.2.0 ]

#### Expected / Desired Behavior / Question
I am expecting the controls to keep working in the upgrade from 3.1.0 to 3.2.0.

#### Observed Behavior
After upgrading from 3.1.0 to 3.2.0, the ListPicker stopped retrieving lists. In the local workbench, it retrieves and displays the mock data, but in the online workbench it just displays a grey area (screenshot below). **I am not seeing any error or network traffic**.
I have a peoplepicker on the same page that works just fine after the upgrade.
![image](https://user-images.githubusercontent.com/40323257/123532881-ef805b00-d6c5-11eb-9502-7b3aad8e0ed5.png)

#### Steps to Reproduce
Create a SPFx 1.12.1 solution
Install spfx controls 3.2.0
Add PeoplePicker and ListPicker

Thanks!

**Comment by AJIXuMuK** [comment] 2021-06-27 19:09
@PathToSharePoint can you share some repro sample? I can't reproduce it.
<img width="703" alt="Screen Shot 2021-06-27 at 12 09 03 PM" src="https://user-images.githubusercontent.com/17036219/123556517-7e31be00-d740-11eb-92d9-b120dce954e8.png">

**Comment by PathToSharePoint** [comment] 2021-06-27 19:16
@AJIXuMuK this is a follow up on issue #848 with the same code sample - just using 1.12.1 and 3.2.0 now.

I followed the documentation and I am wondering if I missed a step. Is anything else needed in addition to SPFx 1.12.1 and controls 3.2.0? A mgt module maybe?

**Comment by AJIXuMuK** [comment] 2021-06-28 01:41
@PathToSharePoint - found the issue.
The fix is in beta version.

**Closed** 2021-06-30 21:26 UTC
Labels: status:fixed-next-drop, type:bug
