### ISSUE TITLE
Taxonomy picker - Collapsible sections

### ISSUE THREAD

**Issue by Whiteshark57** [pnp/sp-dev-fx-controls-react#995] opened 2021-08-19 07:15 UTC
#### Category
[x] Enhancement

[ ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [1.21.1]

#### Expected
Could you please update the taxonomy picker control to allow collapse/expand at all terms level?

#### Observed Behavior
Currently the taxonomy picker control displays all related terms expanded by default which can be very annoying when the list is large.

#### Steps to Reproduce
1- Create a term set with multiple levels.
2- Configure a taxonomy picker control to use this term set.

![image](https://user-images.githubusercontent.com/74719323/130024691-18255461-32d6-4413-a90e-9679a415ffc9.png)

**Comment by joelfmrodrigues** [comment] 2021-09-09 23:08
Hi @Whiteshark57 , many thanks for the suggestion
I will close this item as it's a duplicate of #965 . Feel free to join the discussion on the other item 😊

**Closed** 2021-09-09 23:08 UTC
Labels: Needs: Triage :mag:
