### ISSUE TITLE
TaxonomyPicker Onload validation. Error message is always displayed

### ISSUE THREAD

**Issue by geltapatio** [pnp/sp-dev-fx-controls-react#612] opened 2020-07-13 08:40 UTC
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

####

Please specify what version of the library you are using: [1.9.0  beta version] 

#### Expected / Desired Behavior / Question
The Taxonomy is correct validated [Pnp Taxonomy Picker onload validation](https://github.com/pnp/sp-dev-fx-controls-react/issues/602). after another valid term has been selected, the error message must be removed

#### Observed Behavior
The error message is displayed, even though another valid term has been selected.

#### Steps to Reproduce
add to the Taxonomy Picker component the property validateOnLoad={true}
example <TaxonomyPicker validateOnLoad={true} ...
select another valid term
![errorMessageisalwasysdisplayed](https://user-images.githubusercontent.com/9026810/87282076-2c266700-c4f4-11ea-83a7-f1f122827f6f.jpg)

Thanks!
Luis Miguel Gamiz Espinosa

**Comment by geltapatio** [comment] 2020-07-13 18:03
this bug has already been fixed with [Pull Request](https://github.com/pnp/sp-dev-fx-controls-react/pull/613)

**Comment by AJIXuMuK** [comment] 2020-07-14 00:44
Thank you @geltapatio for reporting the issue and attempt to fix it.
Quick fix has been already pushed and will be available in the next release.

In a meanwhile you can test it in [beta version](https://pnp.github.io/sp-dev-fx-controls-react/beta/).

This bug is caused by implementation of #602. So, if you find any other issues related to `validateOnLoad` - report them in comments of #602.

**Closed by AJIXuMuK** 2020-07-14 00:44 UTC
Labels: Needs: Triage :mag:
