### ISSUE TITLE
Placeholder Control not working in Teams theme

### ISSUE THREAD

**Issue by DJoshi23** [pnp/sp-dev-fx-controls-react#1130] opened 2022-02-15 14:34 UTC
Hi,

I have created SPFx webpart with Placeholder Control and added webpart in Teams application as  a Teams Tab. 

Issue Description : If I change the Teams Theme to High contrast then Placeholder Control not looking properly. Please find the below image for your reference 

![image](https://user-images.githubusercontent.com/86624727/154082654-4261661c-aff1-4b8c-9521-12a9f8d47d1a.png)

and same type of theme issue i am facing in other control as well .

Version : 

SPFX version : 1.12.1
"@pnp/spfx-controls-react": "3.2.1"
"@pnp/spfx-property-controls": "^3.2.0",

Thank you in advance

**Comment by joelfmrodrigues** [comment] 2022-03-14 00:05
Hi @DJoshi23, many thanks for reporting this issue. Would you be interested in submitting a PR?
If so, please keep in mind that the solution has been upgraded to SPFx 1.14.0, which introduces some changes to themes
https://docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.14#web-part-lifecycle-method-for-theme-changes

**Comment by fabiofranzini** [comment] 2022-04-26 07:18
Hi @DJoshi23 and @joelfmrodrigues, I tried by using the latest public version of the library (3.7.2) and for me the result is this one (using a SPFx 1.14.0 solution with a standard Web Part deployed as a Teams Tab):

![PlaceholderInTeamsTab](https://user-images.githubusercontent.com/4202747/165242532-622102ed-118a-486c-8356-f59bf995071e.gif)

So, my advice is to update both this library and the whole SPFx project to the latest version.

However, the classic problem remains, namely the fact that a solution deployed in this way loses some styles such as the font and the real Teams theme applied (a problem that has been well known for a long time).

@joelfmrodrigues what do you think? Is it time for a check to manage the Fluent theme if you are within Teams? Some kind of 
 `ThemeProvider` that applies the Teams theme automatically if you are in Teams and systems finally the question of fonts?
I had already scheduled this type of control since the problem is common.

In this case I can work on a check like that 🙂

**Comment by fabiofranzini** [comment] 2022-04-26 07:18
Hi @DJoshi23 and @joelfmrodrigues, I tried by using the latest public version of the library (3.7.2) and for me the result is this one (using a SPFx 1.14.0 solution with a standard Web Part deployed as a Teams Tab):

![PlaceholderInTeamsTab](https://user-images.githubusercontent.com/4202747/165242532-622102ed-118a-486c-8356-f59bf995071e.gif)

So, my advice is to update both this library and the whole SPFx project to the latest version.

However, the classic problem remains, namely the fact that a solution deployed in this way loses some styles such as the font and the real Teams theme applied (a problem that has been well known for a long time).

@joelfmrodrigues what do you think? Is it time for a check to manage the Fluent theme if you are within Teams? Some kind of 
 `ThemeProvider` that applies the Teams theme automatically if you are in Teams and systems finally the question of fonts?
I had already scheduled this type of control since the problem is common.

In this case I can work on a check like that 🙂

**Comment by joelfmrodrigues** [comment] 2022-04-26 07:45
@fabiofranzini are you referring to a control/helper that would be responsible for the theme on it's own and could be used with any other control to address the issue?

**Comment by fabiofranzini** [comment] 2022-04-26 07:48
> @fabiofranzini are you referring to a control/helper that would be responsible for the theme on it's own and could be used with any other control to address the issue?

Exactly! The same problem exists for the isolated web parts, it could be solved in this way, by wrapping the controls to be used as children of this "new control". This solves the problem universally, even for all fluent controls.

**Comment by joelfmrodrigues** [comment] 2022-04-26 07:52
Yup, that would be amazing to have 🙂 it's definitely one of the pain points with SPFx in my opinion as it's always complex to handle and test across all scenarios.
I will assign this issue to you 🙂 Many thanks!

**Comment by fabiofranzini** [comment] 2022-04-26 13:46
First implementation done:

![EnhancedThemeProvider](https://user-images.githubusercontent.com/4202747/165313512-fd0d534d-5bd6-4ef2-83d4-ba71f79d6e35.gif)

As you can see, the theme colors are applied based on the selected Teams theme, the same thing for fonts too.
The problem with `Placeholder` control (and many others) is that they don't have direct Themes support.

@joelfmrodrigues do you prefer that we leave this issue for the Placeholder control and create a new one for the new control I called "EnhancedThemeProvider"?

**Comment by fabiofranzini** [comment] 2022-04-26 14:11
Ok, I checked the code of the Placeholder control and I realized that sass was used for the style part.
This ensures that the style change is not applied until the page is reloaded, and in fact the behavior is just that. What is best done is:
- add the 'theme' property to the control`s properties
- rewrite the sass part using `@fluentui/merge-styles`
- use the theme property correcly

@joelfmrodrigues If you tell me it's ok, I can start tweaking the control

**Comment by fabiofranzini** [comment] 2022-04-26 15:21
Here is an early version

![EnhancedPlaceholder](https://user-images.githubusercontent.com/4202747/165335118-68760576-96c2-4a71-b03a-624f651bd83c.gif)

**Comment by joelfmrodrigues** [comment] 2022-04-27 09:04
@fabiofranzini sorry for the late reply...
It's looking great! 👏

**Comment by fabiofranzini** [comment] 2022-05-04 09:51
Hi all, just an update: https://github.com/pnp/sp-dev-fx-controls-react/issues/1202#issuecomment-1117124176

**Comment by michaelmaillot** [comment] 2023-08-07 08:45
Hi @DJoshi23,

Following amazing work done by @fabiofranzini, did you had the chance to retry with the EnhancedThemeProvider which is available since 3.9.0?

**Closed** 2023-09-04 11:01 UTC
Labels: area:new-control, Needs: Author Feedback, no-recent-activity, status:working-on-it, type:enhancement
