### ISSUE TITLE
Error on rendering DynamicForm when having a Date Field with internal name starting with underscore ("_")

### ISSUE THREAD

**Issue by Lewin8687** [pnp/sp-dev-fx-controls-react#1738] opened 2024-01-18 20:27 UTC
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Expected / Desired Behavior
The form should be rendered successfully.

#### Observed Behavior
The form dispears and errors show in the console.
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/9344670/1f27dd10-34a5-436f-995e-d9a4fcfb5996)

#### Steps to Reproduce
1. Create an extension using DynamicForm
2. Add OOTB "End Date" or any date field named starting with a number (for example, "1Date") to a content type
3. Add the content type to a document library
4. Create a document out of the content type
5. Attach the custom form to the list content type
6. Add a date value to the new document from Details Pane
7. Open custom form
8. **Issue**: errors show up in console, the form shows and disappears.

#### Investigation
The reason could be the line to get the date value from the list item.
![image](https://github.com/pnp/sp-dev-fx-controls-react/assets/9344670/4b9b7f59-eb4a-4be9-a82c-57e5705eae04)

The key of the date field value in list item is not the same as field internal name. For example, for OOTB date field "End Date", internal name is "_EndDate", but in list item, its saved as "OData__EndDate". Same to other fields which internal name starts with underscore "_". SharePoint will prefix it with "OData_" to make DynamicForm unable to get the value.

**Comment by NishkalankBezawada** [comment] 2024-01-30 17:33
Hello @Lewin8687, 

I have found the issue, and will soon creating a PR on this. 

@joelfmrodrigues @AJIXuMuK @michaelmaillot Please assign this to me. 

Thanks,
Nishkalank

**Comment by NishkalankBezawada** [comment] 2024-01-30 19:39
Hello @Lewin8687,

I have created a PR on this.

#### Problem statement
When a date column is created with an underscore or '_' at the begining, the form is not rendered correctly. For instance, if a column with name '_AccomplishedDate', '1AccomplishedDate' is created, and the list form is not rendered, instead it errors out. 

#### Solution
On investigating the issue, I have created columns as below 

| Column Name              | Type | Internal Name (Retrieved from Item)
| --------------- | --- | ---
| 1EFDate       | DateTime| OData__x0031_EFDate
| 2EFDate       | DateTime| OData__x0032_EFDate
| _EFDate3      | DateTime| OData__EFDate3
| 12312EDate       | DateTime| OData__x0031_2312EDate
| %Test       | Text| OData__x0025_Test
| 1Test      | DateTime| OData__x0031_Test

Since the FieldInternal names are not matching with the Internal names of the columns, this issue is spotted. 
By checking the FieldInternal name as below, and validating, the issue is resolved.

```
        if (fieldName.startsWith('_x') || fieldName.startsWith('_')) {
          fieldName = `OData_${fieldName}`;
        }
```

#### Screenshot

![Issue1738](https://github.com/pnp/sp-dev-fx-controls-react/assets/47456098/2a0ecde6-234d-46c5-92ee-cce7ec436066)


Thanks,
Nishkalank

**Closed** 2024-05-15 20:46 UTC
Labels: status:fixed-next-drop, type:bug
